### ISSUE TITLE
Add CI 

### ISSUE THREAD

**Issue by hzxcaryn** [googleinterns/gpay-group-buy#22]
Add Travis CI to the repo to facilitate the development process. Ensures that all PRs passes all tests and style checks before they can be merged.

**Comment by ifhuang** [comment]
Can you add more info to the issue description?

**Comment by hzxcaryn** [comment]
@ifhuang Haha added a one liner, not too sure what else to add for this! 🤣

**Comment by hzxcaryn** [comment]
@shengdac @ifhuang @erencie  
I need help with [adding Travis CI to the repo](https://travis-ci.org/account/repositories) haha because I don't have admin rights 😭 😭 Would appreciate if you could help me with that! I will deal with add the yaml file so you wouldn't have to do that! :D

**Comment by hzxcaryn** [comment]
@shengdac  have already activated it, thanks! 😄 👍
